### ISSUE TITLE
Shouldn't resolve symlinks

### ISSUE THREAD

**Issue by FichteFoll** [randy3k/AutomaticPackageReloader#13]
When I have a symlinked package in my ST dir and want to reload it, AutomaticPackageReloader isn't active for it because of an `os.path.realpath` call that resolves the symlink and then causes the check for whether the file is within the packages folder to fail.

**Comment by randy3k** [comment]
That's tricky. I put the whole Packages folder as symlink, so resolving it is necessary. A possible solution is to check both the original path and the real path.

**Comment by FichteFoll** [comment]
Hm yes, I guess checking both should cover most situations. I remember doing something similar in some other package of mine.
