### ISSUE TITLE
Less Verbose

### ISSUE THREAD

**Issue by ghost** [randy3k/AutomaticPackageReloader#2]
The plugin is awesome! Thank you very much for it! But could you please add an option to run in silent mode!?

**Comment by randy3k** [comment]
There are a few [options](https://github.com/randy3k/PackageReloader/blob/master/package_reloader.sublime-settings) to control the visibility of the console panel. If you want to completely suppress every output, we should modify [this](https://github.com/randy3k/PackageReloader/blob/1c412ef8cc43656751c6905a3689de41ca4554cf/reloader/reloader.py#L20).

A PR is welcome.
