### ISSUE TITLE
Unable to install via Package Control

### ISSUE THREAD

**Issue by russelldavis** [randy3k/AutomaticPackageReloader#38]
In the console, it shows this error:

**Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/randy3k/AutomaticPackageReloader/zip/1.3.8.**

**Comment by randy3k** [comment]
Fixed https://github.com/randy3k/sublime_packages/commit/db6eb8121fe8236b097e8a599eaba0f5099464a9

Thanks for reporting it.

It may take some time for PC to cache the update.
