### ISSUE TITLE
Only show console on error

### ISSUE THREAD

**Issue by FichteFoll** [randy3k/AutomaticPackageReloader#4]
Instead of opening the console (when it's not open) and then closing it if there was no error (when it was not open), the console should instead *only* be opened if there was an error.

**Comment by FichteFoll** [comment]
Thanks.

Maybe you also want to add some comments to the settings file so we get these sweet PackageDev popups?

https://x0.at/Fx-.mp4

**Comment by randy3k** [comment]
Done.

**Comment by FichteFoll** [comment]
Ah, sorry, the comments will only be parsed when they occur *before* the setting (on their own line). That's the only common style I know of and used by almost everyone.

**Comment by randy3k** [comment]
actually, what feature of PackageDev are you talking about? 🤓

**Comment by FichteFoll** [comment]
This one: https://forum.sublimetext.com/t/looking-for-packagedev-alpha-testers-sublime-syntax-highlighting/24270/39?u=fichtefoll

Like all the other new features, it's currently only available in pre-releases because I'm shuffling around *lots* of things. You should definitely try it out. (To clarify, it shows a popup on hovering settings keys with their description (from comments) and the default value. There's completions now, too.)

You should also join our discord server with lots of active package developers, if you're interested in some chatter: https://discord.gg/HcmwdVK

**Comment by randy3k** [comment]
Cool. Didn't know that there is such of functionality. 

PS: For some reasons, your mp4 didn't play on Mac safari, I have to open chrome.
