### ISSUE TITLE
Command pallet spelling

### ISSUE THREAD

**Issue by deathaxe** [randy3k/AutomaticPackageReloader#5]
The Preference**s** is missing the s here https://github.com/randy3k/AutomaticPackageReloader/blob/master/Default.sublime-commands#L11

All other packages and even default command pallet entries use `Preferences: ... Settings ...`

**Comment by randy3k** [comment]
Good catch!

**Comment by randy3k** [comment]
Mind to submit a PR?

**Comment by deathaxe** [comment]
Wow, quick answer. PR? ... comming soon. 😄
