### ISSUE TITLE
Not working on SublimeLinter

### ISSUE THREAD

**Issue by pykong** [randy3k/AutomaticPackageReloader#9]
I am currently working on a big upgrade to **SublimeLinter**.
Editing any file under the **lint** folder, e.g. lint/persist.py and then triggering reload via the command palette does not result in any reload of the respective file. 

I assume this is not specific to the SublimeLinter package but a general shortcoming of Sublime Text, AutomaticPackageReloader or even the way python handles imports.

**Comment by randy3k** [comment]
I cloned `https://github.com/SublimeLinter/SublimeLinter3` and edited `lint/persist.py`.

AutomaticPackageReloader seems working to me.

```
[Package Reloader] begin ======================================================
reloading plugin SublimeLinter3.commands
[Package Reloader] reloading |-- SublimeLinter3
[Package Reloader] reloading |-- SublimeLinter3.commands
[Package Reloader] reloading | |-- SublimeLinter3.lint
[Package Reloader] reloading | | |-- SublimeLinter3.lint.highlight
[Package Reloader] reloading | | | |-- SublimeLinter3.lint.persist
[Package Reloader] reloading | | | | |-- SublimeLinter3.lint.util
[Package Reloader] reloading | | |-- SublimeLinter3.lint.linter
[Package Reloader] reloading | | |-- SublimeLinter3.lint.python_linter
[Package Reloader] reloading | | |-- SublimeLinter3.lint.ruby_linter
[Package Reloader] reloading | | |-- SublimeLinter3.lint.node_linter
[Package Reloader] reloading | | |-- SublimeLinter3.lint.composer_linter
reloading plugin SublimeLinter3.sublimelinter
[Package Reloader] reloading |-- SublimeLinter3.sublimelinter
[Package Reloader] reloading | |-- SublimeLinter3.lint.queue
SublimeLinter: debug mode: off 
[Package Reloader] installing dummy package
reloading plugin _dummy_package
[Package Reloader] removing dummy package
unloading plugin _dummy_package
[Package Reloader] end --------------------------------------------------------
```

**Comment by pykong** [comment]
@randy3k Thanks for your fast response! Indeed I get the same output still the modification is not included.

You can just insert a `print` statement somewhere in linter.py to reproduce this error.
See whether the print output will appear in SublimeText's console after reloading then.

What other information would you require?

**Comment by randy3k** [comment]
It prints as expected. What OS are you on?

**Comment by pykong** [comment]
I am on Linux Mint 18.x.
I am using the most recent version of Sublime Text = 3149.
I'll see whether I can capture the behavior in an animated gif.

**Comment by pykong** [comment]
0. There is the print statement `print("Old statement")` in a new method of the class Linter in `lint/linter.py`. Below you can see the console pane open.
1. Statement is changed to `print("New statement: Hello Randy!")`
2. File is saved (see status bar message)
3. The command `Automatic Package Reloader: Reload Current Package` is called via command palette. (See output in the console.)
4. The print statement remains unchanged. (The cyclical display of the gif may be a bit confusing. Anyway it ends with several lines of 'Old statement` printed.)

Note this just an example. Any other changes to files in the `lint` subdir remain without effect before restarting Sublime Text, as well.


![apr_bug](https://user-images.githubusercontent.com/20211140/31627548-f26e26c0-b2ad-11e7-91a8-5806d83188cf.gif)

**Comment by randy3k** [comment]
It is odd that `Old Statement` was printed after step 2. What was triggering the reload there?

**Comment by pykong** [comment]
The method is called from - and only from - `get_view_settings`.
But as I stated it does not matter where to put the print statement `lint/linter.py` will only update after a reload of ST itself.

UPDATE: Oddly enough I can now update `highlight.py` still not `linter.py`.

**Comment by randy3k** [comment]
I guess something is mysteriously reloading `linter.py` when it is modified. I said so because  "Old Statement" was printed after step 2.

**Comment by pykong** [comment]
@randy3k Some veterans on discord have been suggesting something along those same lines.
SublimeLinter is a complex beast. 

So, as initially stated it might not necessarily be a bug in **AutomaticPackageReloader**.
If you do not have any clue what this may cause the issue or some handy workaround, I can only
ask @braver or @groteworld (maintainers of SL) for any input on these matters.

(Let them check here first. I can open a different issue on **SL** or **Sublime Text Core** once we have gotten more input.)

**Comment by randy3k** [comment]
It seems that SublimeLinter is handling the reloading to [some extent](https://github.com/SublimeLinter/SublimeLinter3/blob/1319d102b383b64aa9642cd8edb67fcf46e39847/lint/persist.py?utf8=✓#L326). Perhaps, something in SublimeLinter is breaking the use of AutomaticPackageReloader.

**Comment by pykong** [comment]
I'd like to know how **SublimeLinter**'s core devs are actually working.
I can not imagine I am the first one having this problem.
And I do not believe those guys are restarting **ST** for each modification they make.

**Comment by randy3k** [comment]
Contributed linters have to import the SublimeLinter module to function. A restart may be necessarily in one want to see the effects of modifications on SublimeLinter to the linters.

**Comment by braver** [comment]
Yeah, also, SL is old so most of it is maintenance and not like you’re overhauling the entire thing. Other than that I don’t think I’m in a position to tell you more about how reloading actually works here, any more than you already learned.

**Comment by pykong** [comment]
If @groteworld has nothing to contribute in this respect, we may close this issue.
I still wonder how anyone does development on the **SublimeLinter** package.
